# ===========================================
# TEAMMATE PROXY LOCATIONS
# Add each teammate's ngrok endpoint here
# ===========================================

# Henry
location = /_mirror_henry {
    internal;
    proxy_pass https://test$request_uri;
    proxy_set_header Host test;
    proxy_ssl_server_name on;
    proxy_pass_request_body on;
    proxy_set_header Content-Length $content_length;
}

location = /_mirror_kev {
    internal;
    proxy_pass https://test$request_uri;
    proxy_set_header Host test;
    proxy_ssl_server_name on;
    proxy_pass_request_body on;
    proxy_set_header Content-Length $content_length;
}
